version: "3.7"
 
services:
  app-jobfinder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobfinder-api
    command: npm start


networks:
  default:
    external:
      name: nginx-network